language: node_js
node_js: '10'
cache: npm
notifications:
    email: false

script:
    - npm run ci-build
    - echo "mentalhealthweek.se" > out/CNAME
    - touch out/.nojekyll

deploy:
    provider: pages
    skip-cleanup: true
    local-dir: out
    github-token: $GITHUB_TOKEN
    on:
        branch: master

after_deploy:
    - |
        curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
          -H "X-Auth-Email: ${CF_EMAIL}" \
          -H "X-Auth-Key: ${CF_API_KEY}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
